# Generated by Claude Sonnet 4.6 on May 7, 2026

import ROOT
import sys

def extract_first_n_events(input_file, output_file, n_events=10):
    """
    Extract the first n_events from a ROOT file and write them to a new file.

    Args:
        input_file (str): Path to the input ROOT file.
        output_file (str): Path to the output ROOT file.
        n_events (int): Number of events to extract (default: 10).
    """
    # Open the input file
    f_in = ROOT.TFile.Open(input_file, "READ")
    if not f_in or f_in.IsZombie():
        print(f"Error: Could not open input file '{input_file}'")
        sys.exit(1)

    # Access the tree via the trackingNtuple directory
    directory = f_in.Get("trackingNtuple")
    if not directory:
        print("Error: Could not find 'trackingNtuple' directory in the input file.")
        f_in.Close()
        sys.exit(1)

    tree = directory.Get("tree")
    if not tree or not isinstance(tree, ROOT.TTree):
        print("Error: Could not find 'tree' TTree inside 'trackingNtuple'.")
        f_in.Close()
        sys.exit(1)

    print(f"Found TTree 'trackingNtuple/tree' with {tree.GetEntries()} entries")

    total_events = tree.GetEntries()
    if total_events < n_events:
        print(f"Warning: File only contains {total_events} events. Extracting all of them.")
        n_events = total_events

    # Open the output file
    f_out = ROOT.TFile.Open(output_file, "RECREATE")
    if not f_out or f_out.IsZombie():
        print(f"Error: Could not create output file '{output_file}'")
        f_in.Close()
        sys.exit(1)

    # Recreate the trackingNtuple directory and clone the tree into it
    out_dir = f_out.mkdir("trackingNtuple")
    out_dir.cd()
    new_tree = tree.CloneTree(0)  # Clone structure only, no entries

    for i in range(n_events):
        tree.GetEntry(i)
        new_tree.Fill()

    # Write and close files
    f_out.Write()
    f_out.Close()
    f_in.Close()

    print(f"Successfully wrote {n_events} events to '{output_file}'")


if __name__ == "__main__":
    # --- Configuration ---
    INPUT_FILE  = "trackingNtuple-100.root"   # Change to your input file path
    OUTPUT_FILE = "trackingNtuple-50.root"  # Change to your desired output file path
    N_EVENTS    = 50
    # ---------------------

    extract_first_n_events(INPUT_FILE, OUTPUT_FILE, N_EVENTS)